# Generated by Django 2.1.5 on 2020-12-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='title',
        ),
    ]
