# Generated by Django 2.1.5 on 2020-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_remove_fruit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='sold_out',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
