# Generated by Django 2.1.5 on 2020-12-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='MacBook',
        ),
    ]
