# Generated by Django 2.1.5 on 2020-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dairy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk',
            name='fat_perc',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
