# Generated by Django 2.1.5 on 2020-12-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dairy', '0002_milk_fat_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='fat_perc',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
