# Generated by Django 2.1.5 on 2020-12-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='title',
        ),
    ]
